# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class TPList(QtWidgets.QTableWidget):
    def __init__(self, parent=None):
        super(TPList, self).__init__(parent)

    enterPressed = QtCore.pyqtSignal()
        
    def keyPressEvent(self, event):
         k = event.key()
         if(k == QtCore.Qt.Key_Return or k == QtCore.Qt.Key_Enter):
             self.enterPressed.emit()
         else:
             super(TPList, self).keyPressEvent(event)
             
class PList(QtWidgets.QListWidget):
    def __init__(self, parent=None):
        super(PList, self).__init__(parent)

    enterPressed = QtCore.pyqtSignal()
        
    def keyPressEvent(self, event):
         k = event.key()
         if(k == QtCore.Qt.Key_Return or k == QtCore.Qt.Key_Enter):
             self.enterPressed.emit()
         else:
             super(PList, self).keyPressEvent(event)

class Ui_Editor(object):
    _PDATAFIELDS = []
    _ADVANCED_ATT = ["Off", "Hug the Touchline", "False No. 9", "False Full Backs", "Attacking Full Backs", "Wing Rotation", "Tiki-Taka", "Centering Targets"]
    _ADVANCED_DEF = ["Off", "Swarm the Box", "Deep Defensive Line", "Gegenpress", "Tight Marking", "Counter Target"]
    
    valid = QtGui.QIntValidator(0, 99)
    
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(1200, 850)
        Editor.setMinimumSize(QtCore.QSize(1200, 850))
        Editor.setMaximumSize(QtCore.QSize(1200, 850))
        self.centralWidget = QtWidgets.QWidget(Editor)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        
        #TODO: actually implement this some day
        self.deflayout = QtWidgets.QGridLayout(self.tab)
        self.deflayout.setObjectName("deflayout")
        
        self.playerLimiter = QtWidgets.QComboBox(self.tab)
        self.playerLimiter.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.playerLimiter.setObjectName("playerLimiter")
        self.teamDropdown1 = QtWidgets.QComboBox(self.tab)
        self.teamDropdown1.setGeometry(QtCore.QRect(300, 10, 261, 31))
        self.teamDropdown1.setObjectName("teamDropdown1")
        self.teamDropdown1.setMaxVisibleItems(25)
        self.teamDropdown2 = QtWidgets.QComboBox(self.tab)
        self.teamDropdown2.setGeometry(QtCore.QRect(570, 10, 261, 31))
        self.teamDropdown2.setObjectName("teamDropdown2")
        self.teamDropdown2.setMaxVisibleItems(25)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(850, 10, 321, 165))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 55, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 55, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 55, 25))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 55, 25))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 135, 55, 25))
        self.label_6.setObjectName("label_6")
        self.pname = QtWidgets.QLineEdit(self.groupBox)
        self.pname.setGeometry(QtCore.QRect(60, 10, 251, 25))
        self.pname.setObjectName("pname")
        self.pname.setReadOnly(1)
        self.shirtname = QtWidgets.QLineEdit(self.groupBox)
        self.shirtname.setGeometry(QtCore.QRect(60, 40, 251, 25))
        self.shirtname.setObjectName("shirtname")
        self.shirtname.setReadOnly(1)
        self.commid = QtWidgets.QLineEdit(self.groupBox)
        self.commid.setGeometry(QtCore.QRect(60, 70, 181, 25))
        self.commid.setObjectName("commid")
        self.commid.setReadOnly(1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(245, 70, 21, 21))
        self.label_7.setObjectName("label_7")
        self.number = QtWidgets.QLineEdit(self.groupBox)
        self.number.setGeometry(QtCore.QRect(270, 70, 41, 25))
        self.number.setObjectName("number")
        self.number.setReadOnly(1)
        self.club = QtWidgets.QLineEdit(self.groupBox)
        self.club.setGeometry(QtCore.QRect(60, 110, 251, 25))
        self.club.setObjectName("club")
        self.club.setReadOnly(1)
        self.nation = QtWidgets.QLineEdit(self.groupBox)
        self.nation.setGeometry(QtCore.QRect(60, 135, 251, 25))
        self.nation.setObjectName("nation")
        self.nation.setReadOnly(1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(850, 180, 320, 590))
        self.groupBox_2.setMinimumWidth(320)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 110, 25))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 35, 110, 25))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 110, 25))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 85, 110, 25))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 110, 25))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 135, 110, 25))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 160, 110, 25))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 185, 110, 25))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 210, 110, 25))
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 235, 110, 25))
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 260, 110, 25))
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 285, 110, 25))
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 310, 110, 25))
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 335, 110, 25))
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, 360, 110, 25))
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 385, 110, 25))
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(10, 410, 110, 25))
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(10, 435, 110, 25))
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(10, 460, 110, 25))
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(10, 510, 110, 25))
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(10, 485, 110, 25))
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(10, 535, 110, 25))
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(10, 560, 110, 25))
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.attprow = QtWidgets.QLineEdit(self.groupBox_2)
        self.attprow.setGeometry(QtCore.QRect(130, 10, 35, 25))
        self.attprow.setObjectName("attprow")
        self.attprow.setReadOnly(1)
        self.attprow.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.attprow)
        self.defprow = QtWidgets.QLineEdit(self.groupBox_2)
        self.defprow.setGeometry(QtCore.QRect(130, 35, 35, 25))
        self.defprow.setObjectName("defprow")
        self.defprow.setReadOnly(1)
        self.defprow.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.defprow)
        self.goalkeeping = QtWidgets.QLineEdit(self.groupBox_2)
        self.goalkeeping.setGeometry(QtCore.QRect(130, 60, 35, 25))
        self.goalkeeping.setObjectName("goalkeeping")
        self.goalkeeping.setReadOnly(1)
        self.goalkeeping.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.goalkeeping)
        self.dribble = QtWidgets.QLineEdit(self.groupBox_2)
        self.dribble.setGeometry(QtCore.QRect(130, 85, 35, 25))
        self.dribble.setObjectName("dribble")
        self.dribble.setReadOnly(1)
        self.dribble.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.dribble)
        self.finish = QtWidgets.QLineEdit(self.groupBox_2)
        self.finish.setGeometry(QtCore.QRect(130, 110, 35, 25))
        self.finish.setObjectName("finish")
        self.finish.setReadOnly(1)
        self.finish.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.finish)
        self.lowpass = QtWidgets.QLineEdit(self.groupBox_2)
        self.lowpass.setGeometry(QtCore.QRect(130, 135, 35, 25))
        self.lowpass.setObjectName("lowpass")
        self.lowpass.setReadOnly(1)
        self.lowpass.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.lowpass)
        self.loftedpass = QtWidgets.QLineEdit(self.groupBox_2)
        self.loftedpass.setGeometry(QtCore.QRect(130, 160, 35, 25))
        self.loftedpass.setObjectName("loftedpass")
        self.loftedpass.setReadOnly(1)
        self.loftedpass.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.loftedpass)
        self.header = QtWidgets.QLineEdit(self.groupBox_2)
        self.header.setGeometry(QtCore.QRect(130, 185, 35, 25))
        self.header.setObjectName("header")
        self.header.setReadOnly(1)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.header)
        self.swerve = QtWidgets.QLineEdit(self.groupBox_2)
        self.swerve.setGeometry(QtCore.QRect(130, 210, 35, 25))
        self.swerve.setObjectName("swerve")
        self.swerve.setReadOnly(1)
        self.swerve.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.swerve)
        self.catching = QtWidgets.QLineEdit(self.groupBox_2)
        self.catching.setGeometry(QtCore.QRect(130, 235, 35, 25))
        self.catching.setObjectName("catching")
        self.catching.setReadOnly(1)
        self.catching.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.catching)
        self.clearing = QtWidgets.QLineEdit(self.groupBox_2)
        self.clearing.setGeometry(QtCore.QRect(130, 260, 35, 25))
        self.clearing.setObjectName("clearing")
        self.clearing.setReadOnly(1)
        self.clearing.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.clearing)
        self.reflexes = QtWidgets.QLineEdit(self.groupBox_2)
        self.reflexes.setGeometry(QtCore.QRect(130, 285, 35, 25))
        self.reflexes.setObjectName("reflexes")
        self.reflexes.setReadOnly(1)
        self.reflexes.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.reflexes)
        self.bodycontrol = QtWidgets.QLineEdit(self.groupBox_2)
        self.bodycontrol.setGeometry(QtCore.QRect(130, 310, 35, 25))
        self.bodycontrol.setObjectName("bodycontrol")
        self.bodycontrol.setReadOnly(1)
        self.bodycontrol.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.bodycontrol)
        self.physcont = QtWidgets.QLineEdit(self.groupBox_2)
        self.physcont.setGeometry(QtCore.QRect(130, 335, 35, 25))
        self.physcont.setObjectName("physcont")
        self.physcont.setReadOnly(1)
        self.physcont.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.physcont)
        self.kickpower = QtWidgets.QLineEdit(self.groupBox_2)
        self.kickpower.setGeometry(QtCore.QRect(130, 360, 35, 25))
        self.kickpower.setObjectName("kickpower")
        self.kickpower.setReadOnly(1)
        self.kickpower.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.kickpower)
        self.explopower = QtWidgets.QLineEdit(self.groupBox_2)
        self.explopower.setGeometry(QtCore.QRect(130, 385, 35, 25))
        self.explopower.setObjectName("explopower")
        self.explopower.setReadOnly(1)
        self.explopower.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.explopower)
        self.ballcontrol = QtWidgets.QLineEdit(self.groupBox_2)
        self.ballcontrol.setGeometry(QtCore.QRect(130, 410, 35, 25))
        self.ballcontrol.setObjectName("ballcontrol")
        self.ballcontrol.setReadOnly(1)
        self.ballcontrol.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.ballcontrol)
        self.ballwinning = QtWidgets.QLineEdit(self.groupBox_2)
        self.ballwinning.setGeometry(QtCore.QRect(130, 435, 35, 25))
        self.ballwinning.setObjectName("ballwinning")
        self.ballwinning.setReadOnly(1)
        self.ballwinning.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.ballwinning)
        self.jump = QtWidgets.QLineEdit(self.groupBox_2)
        self.jump.setGeometry(QtCore.QRect(130, 460, 35, 25))
        self.jump.setObjectName("jump")
        self.jump.setReadOnly(1)
        self.jump.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.jump)
        self.placekicking = QtWidgets.QLineEdit(self.groupBox_2)
        self.placekicking.setGeometry(QtCore.QRect(130, 485, 35, 25))
        self.placekicking.setObjectName("placekicking")
        self.placekicking.setReadOnly(1)
        self.placekicking.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.placekicking)
        self.coverage = QtWidgets.QLineEdit(self.groupBox_2)
        self.coverage.setGeometry(QtCore.QRect(130, 510, 35, 25))
        self.coverage.setObjectName("coverage")
        self.coverage.setReadOnly(1)
        self.coverage.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.coverage)
        self.stamina = QtWidgets.QLineEdit(self.groupBox_2)
        self.stamina.setGeometry(QtCore.QRect(130, 535, 35, 25))
        self.stamina.setObjectName("stamina")
        self.stamina.setReadOnly(1)
        self.stamina.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.stamina)
        self.speed = QtWidgets.QLineEdit(self.groupBox_2)
        self.speed.setGeometry(QtCore.QRect(130, 560, 35, 25))
        self.speed.setObjectName("speed")
        self.speed.setReadOnly(1)
        self.speed.setAlignment(QtCore.Qt.AlignCenter)
        self._PDATAFIELDS.append(self.speed)
        self.ide = QtWidgets.QLineEdit(self.groupBox_2)
        self.ide.setGeometry(QtCore.QRect(170, 10, 140, 25))
        self.ide.setObjectName("ide")
        self.ide.setReadOnly(1)
        self.facee = QtWidgets.QLineEdit(self.groupBox_2)
        self.facee.setGeometry(QtCore.QRect(170, 35, 140, 25))
        self.facee.setObjectName("facee")
        self.facee.setReadOnly(1)
        self.edite = QtWidgets.QLineEdit(self.groupBox_2)
        self.edite.setGeometry(QtCore.QRect(170, 60, 140, 25))
        self.edite.setObjectName("edite")
        self.edite.setReadOnly(1)
        self.agee = QtWidgets.QLineEdit(self.groupBox_2)
        self.agee.setGeometry(QtCore.QRect(170, 85, 140, 25))
        self.agee.setObjectName("agee")
        self.agee.setReadOnly(1)
        self.bodye = QtWidgets.QLineEdit(self.groupBox_2)
        self.bodye.setGeometry(QtCore.QRect(170, 110, 140, 25))
        self.bodye.setObjectName("bodye")
        self.bodye.setReadOnly(1)
        self.foote = QtWidgets.QLineEdit(self.groupBox_2)
        self.foote.setGeometry(QtCore.QRect(170, 135, 140, 25))
        self.foote.setObjectName("foote")
        self.foote.setReadOnly(1)
        self.pose = QtWidgets.QLineEdit(self.groupBox_2)
        self.pose.setGeometry(QtCore.QRect(170, 160, 140, 25))
        self.pose.setObjectName("pose")
        self.pose.setReadOnly(1)
        self.playerList = PList(self.tab)
        self.playerList.setGeometry(QtCore.QRect(10, 50, 261, 720))
        self.playerList.setMinimumWidth(261)
        self.playerList.setMaximumWidth(261)
        self.playerList.setSelectionMode(1)
        self.playerList.setObjectName("playerList")
        self.teamPlayerList1 = TPList(self.tab)
        self.teamPlayerList1.setGeometry(QtCore.QRect(300, 50, 262, 720))
        self.teamPlayerList1.setMinimumWidth(261)
        self.teamPlayerList1.setMaximumWidth(261)
        self.teamPlayerList1.setObjectName("teamPlayerList1")
        self.teamPlayerList1.setColumnCount(3)
        self.teamPlayerList1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.teamPlayerList1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamPlayerList1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamPlayerList1.setHorizontalHeaderItem(2, item)
        self.teamPlayerList1.horizontalHeader().setSectionResizeMode(2)
        self.teamPlayerList1.horizontalHeader().resizeSection(0, 50)
        self.teamPlayerList1.horizontalHeader().resizeSection(1, 159)
        self.teamPlayerList1.horizontalHeader().resizeSection(2, 50)
        self.teamPlayerList1.verticalHeader().setVisible(False)
        self.teamPlayerList1.verticalHeader().setDefaultSectionSize(25)
        self.teamPlayerList1.setSelectionBehavior(1)
        self.teamPlayerList1.setSelectionMode(1)
        self.teamPlayerList1.setSortingEnabled(0)
        self.teamPlayerList1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.teamPlayerList2 = TPList(self.tab)
        self.teamPlayerList2.setGeometry(QtCore.QRect(570, 50, 261, 720))
        self.teamPlayerList2.setMinimumWidth(261)
        self.teamPlayerList2.setMaximumWidth(261)
        self.teamPlayerList2.setObjectName("teamPlayerList2")
        self.teamPlayerList2.setColumnCount(3)
        self.teamPlayerList2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.teamPlayerList2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamPlayerList2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamPlayerList2.setHorizontalHeaderItem(2, item)
        self.teamPlayerList2.horizontalHeader().setSectionResizeMode(2)
        self.teamPlayerList2.horizontalHeader().resizeSection(0, 50)
        self.teamPlayerList2.horizontalHeader().resizeSection(1, 159)
        self.teamPlayerList2.horizontalHeader().resizeSection(2, 50)
        self.teamPlayerList2.verticalHeader().setVisible(False)
        self.teamPlayerList2.verticalHeader().setDefaultSectionSize(25)
        self.teamPlayerList2.setSelectionBehavior(1)
        self.teamPlayerList2.setSelectionMode(1)
        self.teamPlayerList2.setSortingEnabled(0)
        self.teamPlayerList2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabWidget.addTab(self.tab, "")
        
        '''self.deflayout.addWidget(self.playerLimiter, 0, 0)
        self.deflayout.addWidget(self.playerList, 1, 0)
        self.deflayout.addWidget(self.teamDropdown1, 0, 1)
        self.deflayout.addWidget(self.teamPlayerList1, 1, 1)
        self.deflayout.addWidget(self.teamDropdown2, 0, 2)
        self.deflayout.addWidget(self.teamPlayerList2, 1, 2)
        self.deflayout.addWidget(self.groupBox, 0, 3)
        self.deflayout.addWidget(self.groupBox_2, 1, 3)'''
        
        
        ##
        ##          TAB 3
        ##
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.teamTable = QtWidgets.QTableWidget(self.tab_3)
        self.teamTable.setGeometry(QtCore.QRect(10, 10, 402, 700))
        self.teamTable.setMinimumWidth(402)
        self.teamTable.setMaximumWidth(402)
        self.teamTable.setObjectName("teamTable")
        self.teamTable.setColumnCount(3)
        self.teamTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.teamTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamTable.setHorizontalHeaderItem(2, item)
        self.teamTable.horizontalHeader().setSectionResizeMode(2)
        self.teamTable.horizontalHeader().resizeSection(0, 75)
        self.teamTable.horizontalHeader().resizeSection(1, 75)
        self.teamTable.horizontalHeader().resizeSection(2, 229)
        self.teamTable.verticalHeader().setVisible(False)
        self.teamTable.verticalHeader().setDefaultSectionSize(25)
        self.teamTable.setSelectionBehavior(1)
        self.teamTable.setSelectionMode(1)
        self.teamTable.setSortingEnabled(0)
        self.teamTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(420, 9, 740, 110))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(0, 10, 730, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(10, 40, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.tname = QtWidgets.QLineEdit(self.groupBox_5)
        self.tname.setGeometry(QtCore.QRect(110, 40, 251, 25))
        self.tname.setObjectName("tname")
        self.tname.setMaxLength(70)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.tshort = QtWidgets.QLineEdit(self.groupBox_5)
        self.tshort.setGeometry(QtCore.QRect(110, 70, 251, 25))
        self.tshort.setObjectName("tshort")
        self.tshort.setMaxLength(3)
        self.label_91 = QtWidgets.QLabel(self.groupBox_5)
        self.label_91.setGeometry(QtCore.QRect(380, 40, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.bsse = QtWidgets.QLineEdit(self.groupBox_5)
        self.bsse.setGeometry(QtCore.QRect(470, 40, 110, 25))
        self.bsse.setMaxLength(2)
        self.bsse.setValidator(self.valid)
        self.bsse.setObjectName("bsse")
        self.bssb = QtWidgets.QPushButton(self.groupBox_5)
        self.bssb.setGeometry(QtCore.QRect(600, 40, 75, 25))
        self.bssb.setObjectName("bssb")
        self.label_92 = QtWidgets.QLabel(self.groupBox_5)
        self.label_92.setGeometry(QtCore.QRect(380, 70, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.bslwb = QtWidgets.QPushButton(self.groupBox_5)
        self.bslwb.setGeometry(QtCore.QRect(600, 70, 75, 25))
        self.bslwb.setObjectName("bslwb")
        self.taccept = QtWidgets.QPushButton(self.tab_3)
        self.taccept.setGeometry(QtCore.QRect(130, 720, 150, 50))
        self.taccept.setObjectName("taccept")
        
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(420, 130, 740, 651))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_39 = QtWidgets.QLabel(self.groupBox_8)
        self.label_39.setGeometry(QtCore.QRect(0, 10, 730, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.line_2 = QtWidgets.QFrame(self.groupBox_8)
        self.line_2.setGeometry(QtCore.QRect(0, 40, 730, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_40 = QtWidgets.QLabel(self.groupBox_8)
        self.label_40.setGeometry(QtCore.QRect(0, 60, 730, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_8)
        self.label_41.setGeometry(QtCore.QRect(10, 90, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_8)
        self.label_42.setGeometry(QtCore.QRect(10, 120, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_8)
        self.label_43.setGeometry(QtCore.QRect(10, 150, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_8)
        self.label_44.setGeometry(QtCore.QRect(10, 180, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_8)
        self.label_45.setGeometry(QtCore.QRect(10, 210, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_8)
        self.label_46.setGeometry(QtCore.QRect(260, 90, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_8)
        self.label_47.setGeometry(QtCore.QRect(260, 120, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_8)
        self.label_48.setGeometry(QtCore.QRect(260, 150, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_8)
        self.label_49.setGeometry(QtCore.QRect(260, 180, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_8)
        self.label_50.setGeometry(QtCore.QRect(260, 210, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_8)
        self.label_51.setGeometry(QtCore.QRect(530, 90, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_8)
        self.label_52.setGeometry(QtCore.QRect(530, 120, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_8)
        self.label_53.setGeometry(QtCore.QRect(530, 150, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_8)
        self.label_54.setGeometry(QtCore.QRect(530, 180, 100, 25))
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_53")
        self.label_55 = QtWidgets.QLabel(self.groupBox_8)
        self.label_55.setGeometry(QtCore.QRect(530, 290, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_8)
        self.label_56.setGeometry(QtCore.QRect(260, 380, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.line_3 = QtWidgets.QFrame(self.groupBox_8)
        self.line_3.setGeometry(QtCore.QRect(0, 240, 730, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_57 = QtWidgets.QLabel(self.groupBox_8)
        self.label_57.setGeometry(QtCore.QRect(10, 410, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_8)
        self.label_58.setGeometry(QtCore.QRect(10, 350, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.groupBox_8)
        self.label_59.setGeometry(QtCore.QRect(530, 350, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_8)
        self.label_60.setGeometry(QtCore.QRect(10, 320, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.groupBox_8)
        self.label_61.setGeometry(QtCore.QRect(260, 290, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_8)
        self.label_62.setGeometry(QtCore.QRect(10, 380, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_8)
        self.label_63.setGeometry(QtCore.QRect(260, 410, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_8)
        self.label_64.setGeometry(QtCore.QRect(0, 260, 730, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.groupBox_8)
        self.label_65.setGeometry(QtCore.QRect(260, 320, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_8)
        self.label_66.setGeometry(QtCore.QRect(260, 350, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_8)
        self.label_67.setGeometry(QtCore.QRect(530, 380, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_8)
        self.label_68.setGeometry(QtCore.QRect(530, 320, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_8)
        self.label_69.setGeometry(QtCore.QRect(10, 290, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_8)
        self.label_70.setGeometry(QtCore.QRect(530, 490, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupBox_8)
        self.label_71.setGeometry(QtCore.QRect(260, 580, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.line_4 = QtWidgets.QFrame(self.groupBox_8)
        self.line_4.setGeometry(QtCore.QRect(10, 440, 730, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_72 = QtWidgets.QLabel(self.groupBox_8)
        self.label_72.setGeometry(QtCore.QRect(10, 610, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupBox_8)
        self.label_73.setGeometry(QtCore.QRect(10, 550, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_8)
        self.label_74.setGeometry(QtCore.QRect(530, 550, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.groupBox_8)
        self.label_75.setGeometry(QtCore.QRect(10, 520, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.groupBox_8)
        self.label_76.setGeometry(QtCore.QRect(260, 490, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.groupBox_8)
        self.label_77.setGeometry(QtCore.QRect(10, 580, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.groupBox_8)
        self.label_78.setGeometry(QtCore.QRect(260, 610, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.groupBox_8)
        self.label_79.setGeometry(QtCore.QRect(10, 460, 730, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_79.setFont(font)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.groupBox_8)
        self.label_80.setGeometry(QtCore.QRect(260, 520, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.groupBox_8)
        self.label_81.setGeometry(QtCore.QRect(260, 550, 110, 25))
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.groupBox_8)
        self.label_82.setGeometry(QtCore.QRect(530, 580, 100, 25))
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.groupBox_8)
        self.label_83.setGeometry(QtCore.QRect(530, 520, 100, 25))
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.groupBox_8)
        self.label_84.setGeometry(QtCore.QRect(10, 490, 100, 25))
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.p1srslider = QtWidgets.QSlider(self.groupBox_8)
        self.p1srslider.setGeometry(QtCore.QRect(110, 210, 110, 25))
        self.p1srslider.setFont(font)
        self.p1srslider.setMinimum(1)
        self.p1srslider.setMaximum(10)
        self.p1srslider.setPageStep(1)
        self.p1srslider.setOrientation(QtCore.Qt.Horizontal)
        self.p1srslider.setObjectName("p1srslider")
        self.p1dlslider = QtWidgets.QSlider(self.groupBox_8)
        self.p1dlslider.setGeometry(QtCore.QRect(380, 180, 110, 25))
        self.p1dlslider.setFont(font)
        self.p1dlslider.setMinimum(1)
        self.p1dlslider.setMaximum(10)
        self.p1dlslider.setPageStep(1)
        self.p1dlslider.setProperty("value", 1)
        self.p1dlslider.setOrientation(QtCore.Qt.Horizontal)
        self.p1dlslider.setObjectName("p1dlslider")
        self.p1compslider = QtWidgets.QSlider(self.groupBox_8)
        self.p1compslider.setGeometry(QtCore.QRect(380, 210, 110, 25))
        self.p1compslider.setFont(font)
        self.p1compslider.setMinimum(1)
        self.p1compslider.setMaximum(10)
        self.p1compslider.setPageStep(1)
        self.p1compslider.setProperty("value", 1)
        self.p1compslider.setOrientation(QtCore.Qt.Horizontal)
        self.p1compslider.setObjectName("p1compslider")
        self.p2srslider = QtWidgets.QSlider(self.groupBox_8)
        self.p2srslider.setGeometry(QtCore.QRect(110, 410, 110, 25))
        self.p2srslider.setFont(font)
        self.p2srslider.setMinimum(1)
        self.p2srslider.setMaximum(10)
        self.p2srslider.setPageStep(1)
        self.p2srslider.setProperty("value", 1)
        self.p2srslider.setOrientation(QtCore.Qt.Horizontal)
        self.p2srslider.setObjectName("p2srslider")
        self.p2dlslider = QtWidgets.QSlider(self.groupBox_8)
        self.p2dlslider.setGeometry(QtCore.QRect(380, 380, 110, 25))
        self.p2dlslider.setFont(font)
        self.p2dlslider.setMinimum(1)
        self.p2dlslider.setMaximum(10)
        self.p2dlslider.setPageStep(1)
        self.p2dlslider.setProperty("value", 1)
        self.p2dlslider.setOrientation(QtCore.Qt.Horizontal)
        self.p2dlslider.setObjectName("p2dlslider")
        self.p2compslider = QtWidgets.QSlider(self.groupBox_8)
        self.p2compslider.setGeometry(QtCore.QRect(380, 410, 110, 25))
        self.p2compslider.setFont(font)
        self.p2compslider.setMinimum(1)
        self.p2compslider.setMaximum(10)
        self.p2compslider.setPageStep(1)
        self.p2compslider.setProperty("value", 1)
        self.p2compslider.setOrientation(QtCore.Qt.Horizontal)
        self.p2compslider.setObjectName("p2compslider")
        self.p3srslider = QtWidgets.QSlider(self.groupBox_8)
        self.p3srslider.setGeometry(QtCore.QRect(110, 610, 110, 25))
        self.p3srslider.setFont(font)
        self.p3srslider.setMinimum(1)
        self.p3srslider.setMaximum(10)
        self.p3srslider.setPageStep(1)
        self.p3srslider.setProperty("value", 1)
        self.p3srslider.setOrientation(QtCore.Qt.Horizontal)
        self.p3srslider.setObjectName("p3srslider")
        self.p3dlslider = QtWidgets.QSlider(self.groupBox_8)
        self.p3dlslider.setGeometry(QtCore.QRect(380, 580, 110, 25))
        self.p3dlslider.setFont(font)
        self.p3dlslider.setMinimum(1)
        self.p3dlslider.setMaximum(10)
        self.p3dlslider.setPageStep(1)
        self.p3dlslider.setProperty("value", 1)
        self.p3dlslider.setOrientation(QtCore.Qt.Horizontal)
        self.p3dlslider.setObjectName("p3dlslider")
        self.p3compslider = QtWidgets.QSlider(self.groupBox_8)
        self.p3compslider.setGeometry(QtCore.QRect(380, 610, 110, 25))
        self.p3compslider.setFont(font)
        self.p3compslider.setMinimum(1)
        self.p3compslider.setMaximum(10)
        self.p3compslider.setPageStep(1)
        self.p3compslider.setProperty("value", 1)
        self.p3compslider.setOrientation(QtCore.Qt.Horizontal)
        self.p3compslider.setObjectName("p3compslider")
        self.p1atts = QtWidgets.QPushButton(self.groupBox_8)
        self.p1atts.setGeometry(QtCore.QRect(110, 90, 110, 25))
        self.p1atts.setObjectName("p1atts")
        self.p1buildup = QtWidgets.QPushButton(self.groupBox_8)
        self.p1buildup.setGeometry(QtCore.QRect(110, 120, 110, 25))
        self.p1buildup.setObjectName("p1buildup")
        self.p1atta = QtWidgets.QPushButton(self.groupBox_8)
        self.p1atta.setGeometry(QtCore.QRect(110, 150, 110, 25))
        self.p1atta.setObjectName("p1atta")
        self.p1pos = QtWidgets.QPushButton(self.groupBox_8)
        self.p1pos.setGeometry(QtCore.QRect(110, 180, 110, 25))
        self.p1pos.setObjectName("p1pos")
        self.p1defs = QtWidgets.QPushButton(self.groupBox_8)
        self.p1defs.setGeometry(QtCore.QRect(380, 90, 110, 25))
        self.p1defs.setObjectName("p1defs")
        self.p1contain = QtWidgets.QPushButton(self.groupBox_8)
        self.p1contain.setGeometry(QtCore.QRect(380, 120, 110, 25))
        self.p1contain.setObjectName("p1contain")
        self.p1press = QtWidgets.QPushButton(self.groupBox_8)
        self.p1press.setGeometry(QtCore.QRect(380, 150, 110, 25))
        self.p1press.setObjectName("p1press")
        self.p2atts = QtWidgets.QPushButton(self.groupBox_8)
        self.p2atts.setGeometry(QtCore.QRect(110, 290, 110, 25))
        self.p2atts.setObjectName("p2atts")
        self.p2buildup = QtWidgets.QPushButton(self.groupBox_8)
        self.p2buildup.setGeometry(QtCore.QRect(110, 320, 110, 25))
        self.p2buildup.setObjectName("p2buildup")
        self.p2atta = QtWidgets.QPushButton(self.groupBox_8)
        self.p2atta.setGeometry(QtCore.QRect(110, 350, 110, 25))
        self.p2atta.setObjectName("p2atta")
        self.p2pos = QtWidgets.QPushButton(self.groupBox_8)
        self.p2pos.setGeometry(QtCore.QRect(110, 380, 110, 25))
        self.p2pos.setObjectName("p2pos")
        self.p2defs = QtWidgets.QPushButton(self.groupBox_8)
        self.p2defs.setGeometry(QtCore.QRect(380, 290, 110, 25))
        self.p2defs.setObjectName("p2defs")
        self.p2contain = QtWidgets.QPushButton(self.groupBox_8)
        self.p2contain.setGeometry(QtCore.QRect(380, 320, 110, 25))
        self.p2contain.setObjectName("p2contain")
        self.p2press = QtWidgets.QPushButton(self.groupBox_8)
        self.p2press.setGeometry(QtCore.QRect(380, 350, 110, 25))
        self.p2press.setObjectName("p2press")
        self.p3atts = QtWidgets.QPushButton(self.groupBox_8)
        self.p3atts.setGeometry(QtCore.QRect(110, 490, 110, 25))
        self.p3atts.setObjectName("p3atta")
        self.p3buildup = QtWidgets.QPushButton(self.groupBox_8)
        self.p3buildup.setGeometry(QtCore.QRect(110, 520, 110, 25))
        self.p3buildup.setObjectName("p3buildup")
        self.p3atta = QtWidgets.QPushButton(self.groupBox_8)
        self.p3atta.setGeometry(QtCore.QRect(110, 550, 110, 25))
        self.p3atta.setObjectName("p3atta")
        self.p3pos = QtWidgets.QPushButton(self.groupBox_8)
        self.p3pos.setGeometry(QtCore.QRect(110, 580, 110, 25))
        self.p3pos.setObjectName("p3pos")
        self.p3defs = QtWidgets.QPushButton(self.groupBox_8)
        self.p3defs.setGeometry(QtCore.QRect(380, 490, 110, 25))
        self.p3defs.setObjectName("p3defs")
        self.p3contain = QtWidgets.QPushButton(self.groupBox_8)
        self.p3contain.setGeometry(QtCore.QRect(380, 520, 110, 25))
        self.p3contain.setObjectName("p3contain")
        self.p3press = QtWidgets.QPushButton(self.groupBox_8)
        self.p3press.setGeometry(QtCore.QRect(380, 550, 110, 25))
        self.p3press.setObjectName("p3press")
        self.p1att1 = QtWidgets.QComboBox(self.groupBox_8)
        self.p1att1.setGeometry(QtCore.QRect(610, 90, 111, 22))
        self.p1att1.setObjectName("p1att1")
        i = 0
        for tac in self._ADVANCED_ATT:
            self.p1att1.addItem(tac, i)
            i += 1
        self.p1att2 = QtWidgets.QComboBox(self.groupBox_8)
        self.p1att2.setGeometry(QtCore.QRect(610, 120, 111, 22))
        self.p1att2.setObjectName("p1att2")
        i = 0
        for tac in self._ADVANCED_ATT:
            self.p1att2.addItem(tac, i)
            i += 1
        self.p1def1 = QtWidgets.QComboBox(self.groupBox_8)
        self.p1def1.setGeometry(QtCore.QRect(610, 150, 111, 22))
        self.p1def1.setObjectName("p1def1")
        i = 0
        for tac in self._ADVANCED_DEF:
            self.p1def1.addItem(tac, i)
            i += 1
        self.p1def2 = QtWidgets.QComboBox(self.groupBox_8)
        self.p1def2.setGeometry(QtCore.QRect(610, 180, 111, 22))
        self.p1def2.setObjectName("p1def2")
        i = 0
        for tac in self._ADVANCED_DEF:
            self.p1def2.addItem(tac, i)
            i += 1
        self.p2att1 = QtWidgets.QComboBox(self.groupBox_8)
        self.p2att1.setGeometry(QtCore.QRect(610, 290, 111, 22))
        self.p2att1.setObjectName("p2att1")
        i = 0
        for tac in self._ADVANCED_ATT:
            self.p2att1.addItem(tac, i)
            i += 1
        self.p2att2 = QtWidgets.QComboBox(self.groupBox_8)
        self.p2att2.setGeometry(QtCore.QRect(610, 320, 111, 22))
        self.p2att2.setObjectName("p2att2")
        i = 0
        for tac in self._ADVANCED_ATT:
            self.p2att2.addItem(tac, i)
            i += 1
        self.p2def1 = QtWidgets.QComboBox(self.groupBox_8)
        self.p2def1.setGeometry(QtCore.QRect(610, 350, 111, 22))
        self.p2def1.setObjectName("p2def1")
        i = 0
        for tac in self._ADVANCED_DEF:
            self.p2def1.addItem(tac, i)
            i += 1
        self.p2def2 = QtWidgets.QComboBox(self.groupBox_8)
        self.p2def2.setGeometry(QtCore.QRect(610, 380, 111, 22))
        self.p2def2.setObjectName("p2def2")
        i = 0
        for tac in self._ADVANCED_DEF:
            self.p2def2.addItem(tac, i)
            i += 1
        self.p3att1 = QtWidgets.QComboBox(self.groupBox_8)
        self.p3att1.setGeometry(QtCore.QRect(610, 490, 111, 22))
        self.p3att1.setObjectName("p3att1")
        i = 0
        for tac in self._ADVANCED_ATT:
            self.p3att1.addItem(tac, i)
            i += 1
        self.p3att2 = QtWidgets.QComboBox(self.groupBox_8)
        self.p3att2.setGeometry(QtCore.QRect(610, 520, 111, 22))
        self.p3att2.setObjectName("p3att2")
        i = 0
        for tac in self._ADVANCED_ATT:
            self.p3att2.addItem(tac, i)
            i += 1
        self.p3def1 = QtWidgets.QComboBox(self.groupBox_8)
        self.p3def1.setGeometry(QtCore.QRect(610, 550, 111, 22))
        self.p3def1.setObjectName("p3def1")
        i = 0
        for tac in self._ADVANCED_DEF:
            self.p3def1.addItem(tac, i)
            i += 1
        self.p3def2 = QtWidgets.QComboBox(self.groupBox_8)
        self.p3def2.setGeometry(QtCore.QRect(610, 580, 111, 22))
        self.p3def2.setObjectName("p3def2")
        i = 0
        for tac in self._ADVANCED_DEF:
            self.p3def2.addItem(tac, i)
            i += 1
        self.p1srlabel = QtWidgets.QLabel(self.groupBox_8)
        self.p1srlabel.setGeometry(QtCore.QRect(230, 210, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p1srlabel.setFont(font)
        self.p1srlabel.setObjectName("p1srlabel")
        self.p1dllabel = QtWidgets.QLabel(self.groupBox_8)
        self.p1dllabel.setGeometry(QtCore.QRect(500, 180, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p1dllabel.setFont(font)
        self.p1dllabel.setObjectName("p1dllabel")
        self.p1complabel = QtWidgets.QLabel(self.groupBox_8)
        self.p1complabel.setGeometry(QtCore.QRect(500, 210, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p1complabel.setFont(font)
        self.p1complabel.setObjectName("p1complabel")
        self.p2srlabel = QtWidgets.QLabel(self.groupBox_8)
        self.p2srlabel.setGeometry(QtCore.QRect(230, 410, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p2srlabel.setFont(font)
        self.p2srlabel.setObjectName("p2srlabel")
        self.p2dllabel = QtWidgets.QLabel(self.groupBox_8)
        self.p2dllabel.setGeometry(QtCore.QRect(500, 380, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p2dllabel.setFont(font)
        self.p2dllabel.setObjectName("p2dllabel")
        self.p2complabel = QtWidgets.QLabel(self.groupBox_8)
        self.p2complabel.setGeometry(QtCore.QRect(500, 410, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p2complabel.setFont(font)
        self.p2complabel.setObjectName("p2complabel")
        self.p3srlabel = QtWidgets.QLabel(self.groupBox_8)
        self.p3srlabel.setGeometry(QtCore.QRect(230, 610, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p3srlabel.setFont(font)
        self.p3srlabel.setObjectName("p3srlabel")
        self.p3dllabel = QtWidgets.QLabel(self.groupBox_8)
        self.p3dllabel.setGeometry(QtCore.QRect(500, 580, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p3dllabel.setFont(font)
        self.p3dllabel.setObjectName("p3dllabel")
        self.p3complabel = QtWidgets.QLabel(self.groupBox_8)
        self.p3complabel.setGeometry(QtCore.QRect(500, 610, 16, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.p3complabel.setFont(font)
        self.p3complabel.setObjectName("p3complabel")
        self.tabWidget.addTab(self.tab_3, "")
        
        
        ##
        ##          TAB 2
        ##
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 220, 100))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(0, 10, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.resflags = QtWidgets.QPushButton(self.groupBox_3)
        self.resflags.setGeometry(QtCore.QRect(60, 50, 100, 35))
        self.resflags.setObjectName("resflags")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(470, 10, 220, 101))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.resbcopy = QtWidgets.QPushButton(self.groupBox_4)
        self.resbcopy.setGeometry(QtCore.QRect(60, 50, 100, 35))
        self.resbcopy.setObjectName("resbcopy")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(240, 10, 220, 100))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setGeometry(QtCore.QRect(0, 10, 220, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.restflags = QtWidgets.QPushButton(self.groupBox_6)
        self.restflags.setGeometry(QtCore.QRect(60, 50, 100, 35))
        self.restflags.setObjectName("restflags")
        self.tabWidget.addTab(self.tab_2, "")
        
        
        ##
        ##          REST
        ##
        self.verticalLayout.addWidget(self.tabWidget)
        Editor.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Editor)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        Editor.setMenuBar(self.menuBar)
        self.actionLOAD_OF = QtWidgets.QAction(Editor)
        self.actionLOAD_OF.setObjectName("actionLOAD_OF")
        self.actionSave = QtWidgets.QAction(Editor)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(Editor)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(Editor)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLOAD_OF)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        
        self.menuData = QtWidgets.QMenu(self.menuBar)
        self.menuData.setObjectName("menuData")
        self.actionDump = QtWidgets.QAction(Editor)
        self.actionDump.setObjectName("actionDump")
        self.menuData.addAction(self.actionDump)
        self.menuBar.addAction(self.menuData.menuAction())

        self.retranslateUi(Editor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        Editor.setWindowTitle(_translate("Editor", "Editor"))
        self.label.setText(_translate("Editor", "Name:"))
        self.label_2.setText(_translate("Editor", "Shirt:"))
        self.label_3.setText(_translate("Editor", "Comm:"))
        self.label_4.setText(_translate("Editor", "Club:"))
        self.label_6.setText(_translate("Editor", "Nation:"))
        self.label_7.setText(_translate("Editor", "Nr:"))
        self.label_8.setText(_translate("Editor", "Attacking Prowess"))
        self.label_9.setText(_translate("Editor", "Defensive Prowess"))
        self.label_10.setText(_translate("Editor", "Goalkeeping"))
        self.label_11.setText(_translate("Editor", "Dribbling"))
        self.label_12.setText(_translate("Editor", "Finishing"))
        self.label_13.setText(_translate("Editor", "Low Pass"))
        self.label_14.setText(_translate("Editor", "Lofted Pass"))
        self.label_15.setText(_translate("Editor", "Header"))
        self.label_16.setText(_translate("Editor", "Swerve"))
        self.label_17.setText(_translate("Editor", "Catching"))
        self.label_18.setText(_translate("Editor", "Clearing"))
        self.label_19.setText(_translate("Editor", "Reflexes"))
        self.label_20.setText(_translate("Editor", "Strength on the Ball"))
        self.label_21.setText(_translate("Editor", "Physical Contact"))
        self.label_22.setText(_translate("Editor", "Kicking Power"))
        self.label_23.setText(_translate("Editor", "Explosive Power"))
        self.label_24.setText(_translate("Editor", "Ball Control"))
        self.label_25.setText(_translate("Editor", "Ball Winning"))
        self.label_26.setText(_translate("Editor", "Jump"))
        self.label_27.setText(_translate("Editor", "Coverage"))
        self.label_28.setText(_translate("Editor", "Place Kicking"))
        self.label_29.setText(_translate("Editor", "Stamina"))
        self.label_30.setText(_translate("Editor", "Speed"))
        self.ide.setText(_translate("Editor", "ID:"))
        self.facee.setText(_translate("Editor", "Face:"))
        self.edite.setText(_translate("Editor", "Edit:"))
        self.agee.setText(_translate("Editor", "Age:"))
        self.bodye.setText(_translate("Editor", "Body:"))
        self.foote.setText(_translate("Editor", "Foot:"))
        self.pose.setText(_translate("Editor", "Pos:"))
        item = self.teamPlayerList1.horizontalHeaderItem(0)
        item.setText(_translate("Editor", "Pos"))
        item = self.teamPlayerList1.horizontalHeaderItem(1)
        item.setText(_translate("Editor", "Name"))
        item = self.teamPlayerList1.horizontalHeaderItem(2)
        item.setText(_translate("Editor", "Nr"))
        
        
        item = self.teamPlayerList2.horizontalHeaderItem(0)
        item.setText(_translate("Editor", "Pos"))
        item = self.teamPlayerList2.horizontalHeaderItem(1)
        item.setText(_translate("Editor", "Name"))
        item = self.teamPlayerList2.horizontalHeaderItem(2)
        item.setText(_translate("Editor", "Nr"))
        
        
        item = self.teamTable.horizontalHeaderItem(0)
        item.setText(_translate("Editor", "ID"))
        item = self.teamTable.horizontalHeaderItem(1)
        item.setText(_translate("Editor", "Short"))
        item = self.teamTable.horizontalHeaderItem(2)
        item.setText(_translate("Editor", "Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Editor", "Players and Transfers"))
        
        
        self.label_32.setText(_translate("Editor", "General"))
        self.label_33.setText(_translate("Editor", "Team Name:"))
        self.label_34.setText(_translate("Editor", "Short:"))
        self.label_91.setText(_translate("Editor", "Bulk set stats:"))
        self.bssb.setText(_translate("Editor", "Set"))
        self.label_92.setText(_translate("Editor", "Bulk set Left Wrist Tape:"))
        self.bslwb.setText(_translate("Editor", "Set"))
        self.taccept.setText(_translate("Editor", "Accept"))
        self.label_39.setText(_translate("Editor", "Tactics"))
        self.label_40.setText(_translate("Editor", "Preset 1"))
        self.label_41.setText(_translate("Editor", "Attacking Style:"))
        self.label_42.setText(_translate("Editor", "Build Up:"))
        self.label_43.setText(_translate("Editor", "Attacking Area:"))
        self.label_44.setText(_translate("Editor", "Positioning:"))
        self.label_45.setText(_translate("Editor", "Support Range"))
        self.label_46.setText(_translate("Editor", "Defensive Style:"))
        self.label_47.setText(_translate("Editor", "Containment Area:"))
        self.label_48.setText(_translate("Editor", "Pressuring:"))
        self.label_49.setText(_translate("Editor", "Defensive Line:"))
        self.label_50.setText(_translate("Editor", "Compactness:"))
        self.label_51.setText(_translate("Editor", "Offensive 1:"))
        self.label_52.setText(_translate("Editor", "Offensive 2:"))
        self.label_53.setText(_translate("Editor", "Defensive 1:"))
        self.label_54.setText(_translate("Editor", "Defensive 2:"))
        self.label_55.setText(_translate("Editor", "Offensive 1:"))
        self.label_56.setText(_translate("Editor", "Defensive Line:"))
        self.label_57.setText(_translate("Editor", "Support Range"))
        self.label_58.setText(_translate("Editor", "Attacking Area:"))
        self.label_59.setText(_translate("Editor", "Defensive 1:"))
        self.label_60.setText(_translate("Editor", "Build Up:"))
        self.label_61.setText(_translate("Editor", "Defensive Style:"))
        self.label_62.setText(_translate("Editor", "Positioning:"))
        self.label_63.setText(_translate("Editor", "Compactness:"))
        self.label_64.setText(_translate("Editor", "Preset 2"))
        self.label_65.setText(_translate("Editor", "Containment Area:"))
        self.label_66.setText(_translate("Editor", "Pressuring:"))
        self.label_67.setText(_translate("Editor", "Defensive 2:"))
        self.label_68.setText(_translate("Editor", "Offensive 2:"))
        self.label_69.setText(_translate("Editor", "Attacking Style:"))
        self.label_70.setText(_translate("Editor", "Offensive 1:"))
        self.label_71.setText(_translate("Editor", "Defensive Line:"))
        self.label_72.setText(_translate("Editor", "Support Range"))
        self.label_73.setText(_translate("Editor", "Attacking Area:"))
        self.label_74.setText(_translate("Editor", "Defensive 1:"))
        self.label_75.setText(_translate("Editor", "Build Up:"))
        self.label_76.setText(_translate("Editor", "Defensive Style:"))
        self.label_77.setText(_translate("Editor", "Positioning:"))
        self.label_78.setText(_translate("Editor", "Compactness:"))
        self.label_79.setText(_translate("Editor", "Preset 3"))
        self.label_80.setText(_translate("Editor", "Containment Area:"))
        self.label_81.setText(_translate("Editor", "Pressuring:"))
        self.label_82.setText(_translate("Editor", "Defensive 2:"))
        self.label_83.setText(_translate("Editor", "Offensive 2:"))
        self.label_84.setText(_translate("Editor", "Attacking Style:"))
        self.p1atts.setText(_translate("Editor", "Counter Attack"))
        self.p1buildup.setText(_translate("Editor", "Long-Pass"))
        self.p1atta.setText(_translate("Editor", "Wide"))
        self.p1pos.setText(_translate("Editor", "Maintain Formation"))
        self.p1defs.setText(_translate("Editor", "Frontline Pressure"))
        self.p1contain.setText(_translate("Editor", "Middle"))
        self.p1press.setText(_translate("Editor", "Aggressive"))
        self.p2atts.setText(_translate("Editor", "Counter Attack"))
        self.p2buildup.setText(_translate("Editor", "Long-Pass"))
        self.p2atta.setText(_translate("Editor", "Wide"))
        self.p2pos.setText(_translate("Editor", "Maintain Formation"))
        self.p2defs.setText(_translate("Editor", "Frontline Pressure"))
        self.p2contain.setText(_translate("Editor", "Middle"))
        self.p2press.setText(_translate("Editor", "Aggressive"))
        self.p3atts.setText(_translate("Editor", "Counter Attack"))
        self.p3buildup.setText(_translate("Editor", "Long-Pass"))
        self.p3atta.setText(_translate("Editor", "Wide"))
        self.p3pos.setText(_translate("Editor", "Maintain Formation"))
        self.p3defs.setText(_translate("Editor", "Frontline Pressure"))
        self.p3contain.setText(_translate("Editor", "Middle"))
        self.p3press.setText(_translate("Editor", "Aggressive"))
        self.p1srlabel.setText(_translate("Editor", "1"))
        self.p1dllabel.setText(_translate("Editor", "1"))
        self.p1complabel.setText(_translate("Editor", "1"))
        self.p2srlabel.setText(_translate("Editor", "1"))
        self.p2dllabel.setText(_translate("Editor", "1"))
        self.p2complabel.setText(_translate("Editor", "1"))
        self.p3srlabel.setText(_translate("Editor", "1"))
        self.p3dllabel.setText(_translate("Editor", "1"))
        self.p3complabel.setText(_translate("Editor", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Editor", "Teams"))
        
        
        self.label_31.setText(_translate("Editor", "Flags"))
        self.resflags.setText(_translate("Editor", "Reset All"))
        self.label_5.setText(_translate("Editor", "Base Copy"))
        self.resbcopy.setText(_translate("Editor", "Fix IDs"))
        self.label_35.setText(_translate("Editor", "Team Flags"))
        self.restflags.setText(_translate("Editor", "Reset All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Editor", "4CC"))
        
        
        self.menuFile.setTitle(_translate("Editor", "File"))
        self.menuData.setTitle(_translate("Editor", "Data"))
        self.actionLOAD_OF.setText(_translate("Editor", "Load OF"))
        self.actionDump.setText(_translate("Editor", "Dump Database to CSV"))
        self.actionSave.setText(_translate("Editor", "Save"))
        self.actionSave_As.setText(_translate("Editor", "Save As..."))
        self.actionExit.setText(_translate("Editor", "Exit"))

